import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

import { root, jiti } from "./lib/loader.mjs";

const hooks = new Map(); const commands = new Map(); const shortcuts = new Map();
const ALL = ["question", "read", "grep", "find", "ls", "write", "edit", "bash", "subagent", "web_search", "lens_diagnostics", "pi_lens_activate_tools", "ast_grep_replace", "lens_diagnostic_mark", "symbol_search", "debug"];
let active = [...ALL];
const modes = await jiti.import(path.join(root, "extensions/modes/index.ts"));
modes.default({ on: (n, fn) => hooks.set(n, fn), registerCommand: (n, def) => commands.set(n, def), registerShortcut: (key, def) => shortcuts.set(key, def), getActiveTools: () => active, setActiveTools: names => { active = names; } });
const call = (toolName, input = {}) => hooks.get("tool_call")({ toolName, input });
let checks = 0;
const check = (cond, label) => { assert.ok(cond, "FAIL: " + label); checks++; console.log("ok   " + label); };

const statuses = new Map();
const ctx = { cwd: path.dirname(root), hasUI: true, ui: { notify() {}, setStatus: (key, text) => statuses.set(key, text), theme: { fg: (_color, text) => text } } };
await hooks.get("session_start")({}, ctx);
check((await call("debug", { program: "target/debug/app" })).block, "discuss blocks debugger execution");
check(statuses.get("harness-mode") === "MODE: DISCUSS · Tab", "footer displays default mode before the first prompt");
check(statuses.get("harness-speed") === "Speed: — tok/s", "footer shows speed before usage is available");
await hooks.get("before_provider_request")({ payload: {} }, ctx);
check(statuses.get("harness-speed") === "Speed: TTFT … · — tok/s", "footer waits for the first token after the request is sent");
await new Promise(r => setTimeout(r, 5));
await hooks.get("message_update")({ message: { role: "assistant", usage: { output: 0 } }, assistantMessageEvent: { type: "text_delta" } }, ctx);
check(/^Speed: TTFT \d+\.\ds · streaming…$/.test(statuses.get("harness-speed")), "footer shows TTFT and streaming while token usage is pending");
await new Promise(r => setTimeout(r, 5));
await hooks.get("message_end")({ message: { role: "assistant", usage: { output: 100 } } }, ctx);
check(/^Speed: TTFT \d+\.\ds · \d+\.\d tok\/s$/.test(statuses.get("harness-speed")), "completed response displays TTFT and generation speed");
const { TokenSpeed } = await jiti.import(path.join(root, "extensions/lib/token-speed.ts"));
const speed = new TokenSpeed();
speed.start(1000);
speed.firstToken(3000);
check(speed.ttft === 2, "TTFT is request-to-first-token time");
check(speed.update(101, 5000) === 50, "generation speed excludes prompt processing");
speed.firstToken(4000);
check(speed.ttft === 2, "later deltas do not move the first-token time");
speed.start(4000);
check(speed.update(100, 5000) === undefined, "no rate before the first token");
speed.firstToken(4000);
check(speed.update(undefined, 5000) === undefined, "missing usage does not invent a rate");
check(speed.update(100, 4000) === undefined, "zero duration does not produce an infinite rate");

await hooks.get("before_agent_start")({});
check(active.includes("read") && active.includes("grep") && active.includes("ls") && active.includes("find") && active.includes("lens_diagnostics") && active.includes("symbol_search"), "discuss keeps read-only repo + code-intel tools");
check(!active.includes("bash") && !active.includes("edit") && !active.includes("write") && !active.includes("ast_grep_replace") && !active.includes("pi_lens_activate_tools"), "discuss drops bash/edit/write/activator/mutating lens tool");
check((await call("bash", { command: "ls" })).block === true, "gate blocks bash in discuss");
check((await call("edit", {})).block === true, "gate blocks edit in discuss");
check((await call("write", {})).block === true, "gate blocks write in discuss");
check((await call("read", { path: "HARNESS.md" })) === undefined, "gate allows read in discuss");
check((await call("find", { pattern: "x" })) === undefined, "gate allows find in discuss");
check((await call("new_plugin_write", {})).block === true, "unknown plugin tools fail closed in discuss");
check((await call("subagent", { agent: "discuss" })) === undefined, "discuss dispatches the discuss agent");
check((await call("subagent", { agent: "scout" })).block === true, "discuss blocks scout");
const promptEvent = () => ({ systemPromptOptions: { cwd: "/", sections: { other: "kept" } } });
const first = promptEvent(); await hooks.get("before_agent_start")(first);
check(first.systemPromptOptions.sections.other === "kept" && first.systemPromptOptions.sections.harness_mode.startsWith("[MODE: DISCUSS]") && first.systemPromptOptions.sections.harness_mode.includes("cannot run commands"), "discuss instructions are a system-prompt section");
const again = promptEvent(); await hooks.get("before_agent_start")(again);
check(again.systemPromptOptions.sections.harness_mode === first.systemPromptOptions.sections.harness_mode, "mode section is byte-stable within a mode (prompt cache)");
check(!hooks.has("context"), "no context hook rewrites history (prompt cache)");

await commands.get("mode").handler("plan", ctx);
check(statuses.get("harness-mode") === "MODE: PLAN · Tab", "mode command updates the footer");
const planPrompt = promptEvent(); await hooks.get("before_agent_start")(planPrompt);
check(planPrompt.systemPromptOptions.sections.harness_mode.includes("prompts/plan.md") && planPrompt.systemPromptOptions.sections.harness_mode.includes("one goal at a time"), "plan mode routes implementation plans to the mission/goal planner");
check(active.includes("question") && planPrompt.systemPromptOptions.sections.harness_mode.includes("question tool"), "plan mode keeps the question tool and uses it for interviews");
check(planPrompt.systemPromptOptions.sections.harness_mode.includes("Never say you will start work this mode cannot do"), "plan mode does not promise work it cannot do");
const globBlock = await call("bash", { command: "rg -n reshield ../orchestrator/test* 2>/dev/null" });
check(globBlock.block && globBlock.reason.includes("globs") && globBlock.reason.includes("2>/dev/null"), "plan block reason explains the read-only rules");
check(active.includes("bash") && active.includes("read") && !active.includes("edit") && !active.includes("write"), "plan keeps read+bash, drops edit/write");
for (const tool of ["ast_grep_replace", "lens_diagnostic_mark", "pi_lens_activate_tools"]) {
  check(!active.includes(tool), `plan removes ${tool}`);
  check((await call(tool, { apply: true, tools: ["ast_grep_replace"] })).block === true, `plan gate blocks ${tool} even if reactivated`);
}
check(active.includes("lens_diagnostics") && active.includes("symbol_search"), "plan keeps read-only code intelligence");
check((await call("bash", { command: "sort -o result input" })).block === true, "plan blocks mutating bash");
check((await call("bash", { command: "ls" })) === undefined, "plan allows read-only bash");
check((await call("new_plugin_write", {})).block === true, "unknown plugin tools fail closed in plan");
check((await call("lsp_navigation", { operation: "references" })) === undefined, "read-only LSP navigation stays available");
for (const operation of ["rename", "rename_file", "executeCommand", "codeAction"]) check((await call("lsp_navigation", { operation })).block === true, `mutating LSP ${operation} blocked`);
check((await call("subagent", { agent: "executor" })).block === true, "plan blocks executor");
await commands.get("mode").handler("execute", ctx);
check(active.length === ALL.length, "execute restores the full tool set");
const execPrompt = promptEvent(); await hooks.get("before_agent_start")(execPrompt);
check(execPrompt.systemPromptOptions.sections.harness_mode.includes("prompts/plan.md"), "execute mode also routes implementation plans to the planner");
for (const tool of ["ast_grep_replace", "lens_diagnostic_mark", "pi_lens_activate_tools"]) {
  check((await call(tool, { apply: true })) === undefined, `execute allows ${tool}`);
}
check((await call("bash", { command: "git commit -m x" })) === undefined, "execute allows mutating bash");
check(shortcuts.has("tab"), "Tab is registered for mode cycling");
await shortcuts.get("tab").handler(ctx);
check(statuses.get("harness-mode") === "MODE: DISCUSS · Tab", "Tab updates the footer to discuss");
check(!active.includes("write") && !active.includes("bash"), "Tab cycles execute to discuss");
await shortcuts.get("tab").handler(ctx);
check(statuses.get("harness-mode") === "MODE: PLAN · Tab", "Tab updates the footer to plan");
check(active.includes("bash") && !active.includes("write"), "Tab cycles discuss to plan");
await shortcuts.get("tab").handler(ctx);
check(statuses.get("harness-mode") === "MODE: EXECUTE · Tab", "Tab updates the footer to execute");
check(active.length === ALL.length, "Tab cycles plan to execute");
check(JSON.parse(fs.readFileSync(path.join(root, "keybindings.json"), "utf8"))["tui.input.tab"] === "ctrl+space", "autocomplete moves to Ctrl+Space");
const questionModule = await jiti.import(path.join(root, "extensions/question.ts"));
const plain = { fg: (_c, t) => t, bold: t => t };
const KEY = { up: "\x1b[A", down: "\x1b[B", enter: "\r", space: " ", esc: "\x1b" };
const opts = [{ label: "Yes (Recommended)", description: "funds stay in wallet" }, { label: "No" }];
const pick = (multi, keys) => { let out = "pending"; const p = questionModule.createPicker("Keep close semantics?", opts, multi, plain, r => { out = r; }, () => {}); for (const k of keys) p.handleInput(k); return { out, view: p.render(80).join("\n") }; };
const radio = pick(false, []);
check(radio.view.includes("( ) 2. No") && radio.view.includes("(•) 1. Yes") && radio.view.includes(`3. ${questionModule.OTHER_OPTION}`) && radio.view.includes("funds stay in wallet"), "single question renders radio rows, descriptions and a final type-your-own row");
check(JSON.stringify(pick(false, [KEY.down, KEY.enter]).out) === JSON.stringify({ indices: [1], other: false }), "arrow + Enter selects one option");
check(JSON.stringify(pick(false, ["1"]).out) === JSON.stringify({ indices: [0], other: false }), "number key selects directly");
const boxes = pick(true, [KEY.space, KEY.down, KEY.down]);
check(boxes.view.includes("[x] 1. Yes") && boxes.view.includes("[ ] 2. No") && boxes.out === "pending", "multi-select renders checkboxes and Space toggles without submitting");
check(JSON.stringify(pick(true, [KEY.space, KEY.up, KEY.space, KEY.enter]).out) === JSON.stringify({ indices: [0], other: true }), "multi-select returns checked options plus the type-your-own row");
const empty = pick(true, [KEY.enter]);
check(empty.out === "pending" && empty.view.includes("Select at least one"), "multi-select refuses an empty submit with a hint");
check(pick(true, ["2", "2", "1", KEY.enter]).out.indices.join() === "0", "number keys toggle in multi-select");
check(pick(false, [KEY.esc]).out === null, "Esc cancels");
const withContext = questionModule.createPicker("Confirm Goal 1?", opts, false, plain, () => {}, () => {}, "# Goal 01: Reshield queue\nOutcome: jobs are accepted\n# Decisions\n1. Ack means ownership").render(80).join("\n");
check(withContext.indexOf("Goal 01: Reshield queue") < withContext.indexOf("Confirm Goal 1?") && withContext.includes("1. Ack means ownership") && !withContext.includes("# Goal"), "context renders above the question with headings");
let questionTool; questionModule.default({ registerTool: tool => { questionTool = tool; } });
const run = (result, typed, multiSelect = true, mode = "tui") => questionTool.execute("q", { question: "Which checks?", options: opts, multiSelect }, undefined, undefined, { hasUI: true, mode, ui: { custom: async () => result, input: async () => typed } });
const both = await run({ indices: [0, 1], other: true }, "  fuzz too  ");
check(JSON.stringify(both.details.answers) === JSON.stringify(["Yes (Recommended)", "No", "fuzz too"]) && both.content[0].text.includes("User wrote: fuzz too"), "tool returns every checked label plus the typed answer");
check((await run({ indices: [1], other: false })).content[0].text === "User selected: No", "tool reports a single selection");
const kept = questionTool.renderResult({ content: [], details: { question: "Confirm?", context: "# Goal 01\nOutcome: x", answers: ["Confirm"] } }, {}, plain).render(80).join("\n");
check(kept.includes("Goal 01") && kept.includes("Outcome: x") && kept.includes("✓ Confirm"), "context and answer stay in the chat after the picker closes");
check((await run(null)).details.answers === null, "cancelled question returns no answer");
check((await run({ indices: [], other: true }, "")).details.answers === null, "empty typed answer counts as cancel");
check((await run({ indices: [0], other: false }, "", false, "rpc")).content[0].text.includes("plain text"), "question falls back to plain text outside the TUI");
console.log(`\nPassed ${checks} mode checks.`);
