import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { root, jiti } from "./lib/loader.mjs";

const { runHarnessAction, fingerprint } = await jiti.import(path.join(root, "extensions/lib/verification.ts"));
const { acquireWriter } = await jiti.import(path.join(root, "extensions/lib/writer-lock.ts"));
const { loadRuntimeConfig } = await jiti.import(path.join(root, "extensions/subagent/runtime.ts"));
const { createLocalBashOperations } = await jiti.import("@earendil-works/pi-coding-agent");
const ops = createLocalBashOperations(); // Offline test fixtures only; live tool receives sandbox operations.
const fixture = fs.mkdtempSync(path.join(os.tmpdir(), "pi-verification-"));
let checks = 0;
const check = (condition, label) => { assert.ok(condition, label); checks++; };
try {
  const repo = path.join(fixture, "repo"); fs.mkdirSync(repo);
  const git = args => execFileSync("git", args, { cwd: repo, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
  git(["init"]); git(["config", "user.name", "Harness Test"]); git(["config", "user.email", "test@example.invalid"]);
  fs.writeFileSync(path.join(repo, "code.txt"), "initial\n"); git(["add", "code.txt"]); git(["commit", "-m", "initial"]);
  const store = path.join(fixture, "evidence");
  const action = input => runHarnessAction({ run: "C1", ...input }, repo, ops, undefined, store);
  const lock = acquireWriter(repo, path.join(fixture, "locks"));
  assert.throws(() => acquireWriter(repo, path.join(fixture, "locks")), /active writer/); checks++;
  lock.release(); acquireWriter(repo, path.join(fixture, "locks")).release(); checks++;
  await action({ action: "define", contract: "Required tests pass for this exact checkout", checks: [{ id: "unit", command: "test -f code.txt", property: "code exists" }, { id: "seed", command: "test \"$HARNESS_SEED\" = 'repro 42'", property: "seed passed literally" }] });
  await assert.rejects(action({ action: "define", contract: "changed", checks: [] }), /already exists/); checks++;
  await assert.rejects(action({ action: "verify", check: "unit" }), /implementation complete/); checks++;
  fs.writeFileSync(path.join(repo, "code.txt"), "implemented\n");
  await action({ action: "implemented" });
  await action({ action: "verify", check: "unit" });
  await assert.rejects(action({ action: "complete" }), /seed/); checks++;
  const failed = await action({ action: "verify", check: "seed", seed: "wrong" });
  check(!failed.evidence.passed && failed.evidence.exitCode !== 0, "failed commands produce durable failure evidence");
  await action({ action: "verify", check: "seed", seed: "repro 42" });
  check((await action({ action: "complete" })).phase === "verified", "all required checks unlock completion");
  fs.writeFileSync(path.join(repo, "untracked.txt"), "new code\n");
  check(!(await action({ action: "status" })).evidenceFresh, "untracked edits stale evidence");
  await assert.rejects(action({ action: "complete" }), /stale/); checks++;
  for (const id of ["unit", "seed"]) await action({ action: "verify", check: id, seed: "repro 42" });
  await assert.rejects(action({ action: "checkpoint", files: ["code.txt"], message: "C1" }), /outside checkpoint/); checks++;
  git(["add", "code.txt"]);
  await assert.rejects(action({ action: "checkpoint", files: ["code.txt", "untracked.txt"], message: "C1" }), /already contains/); checks++;
  git(["restore", "--staged", "code.txt"]);
  const committed = await action({ action: "checkpoint", files: ["code.txt", "untracked.txt"], message: "C1" });
  check(committed.phase === "committed" && committed.commit === git(["rev-parse", "HEAD"]).trim(), "checkpoint commits only verified scoped files");
  check((await action({ action: "complete" })).phase === "committed", "committed checkpoint can be revalidated");
  fs.appendFileSync(committed.evidence.filter(item => item.check === "unit").at(-1).outputPath, "tampered");
  await assert.rejects(action({ action: "complete" }), /output missing or changed/); checks++;
  await action({ action: "define", run: "mutates", contract: "checks cannot change source", checks: [{ id: "bad", command: "printf changed >> code.txt", property: "source unchanged" }] });
  await action({ action: "implemented", run: "mutates" });
  check(!(await action({ action: "verify", run: "mutates", check: "bad" })).evidence.passed, "passing command that changes source fails verification");
  const before = await fingerprint(repo, ops);
  fs.unlinkSync(path.join(repo, "untracked.txt"));
  check(before !== await fingerprint(repo, ops), "tracked deletion changes fingerprint");
  fs.symlinkSync("code.txt", path.join(repo, "source-link"));
  const linkedBefore = await fingerprint(repo, ops);
  fs.appendFileSync(path.join(repo, "code.txt"), "linked-change");
  check(linkedBefore !== await fingerprint(repo, ops), "file symlinks include referenced content");
  fs.writeFileSync(path.join(fixture, "outside"), "external source");
  fs.symlinkSync(path.join(fixture, "outside"), path.join(repo, "external-link"));
  await assert.rejects(fingerprint(repo, ops), /external or protected symlink/); checks++;
  fs.unlinkSync(path.join(repo, "external-link"));
  const moduleRepo = path.join(fixture, "module"); fs.mkdirSync(moduleRepo);
  const moduleGit = args => execFileSync("git", args, { cwd: moduleRepo, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
  moduleGit(["init"]); moduleGit(["config", "user.name", "Harness Test"]); moduleGit(["config", "user.email", "test@example.invalid"]);
  fs.writeFileSync(path.join(moduleRepo, "module.txt"), "module source"); moduleGit(["add", "module.txt"]); moduleGit(["commit", "-m", "module"]);
  git(["-c", "protocol.file.allow=always", "submodule", "add", moduleRepo, "module"]);
  const moduleBefore = await fingerprint(repo, ops);
  fs.appendFileSync(path.join(repo, "module/module.txt"), "changed");
  check(moduleBefore !== await fingerprint(repo, ops), "submodule content edits stale parent evidence");
  const runtimeFile = path.join(fixture, "runtime.json");
  fs.writeFileSync(runtimeFile, JSON.stringify({ maxTurns: 0 })); assert.throws(() => loadRuntimeConfig(runtimeFile), /Invalid maxTurns/); checks++;
  fs.writeFileSync(runtimeFile, JSON.stringify({ thinking: { scout: "bogus" } })); assert.throws(() => loadRuntimeConfig(runtimeFile), /thinking level/); checks++;
  fs.writeFileSync(runtimeFile, JSON.stringify({ maxTurns: 5 })); check(loadRuntimeConfig(runtimeFile).maxTurns === 5, "runtime edits reload");
  console.log(`Passed ${checks} verification and writer-lock checks.`);
} finally { fs.rmSync(fixture, { recursive: true, force: true }); }
